language: ruby
rvm:
- 2.3.1
notifications:
  slack:
    secure: rBeq0yIU7UD1f42RcOHpux1k1wY9Jh4wYlnYQ1RUVw3EuFPf8b+G4T255BVCsSZiBPlb7ki565oIfCfxYM22cANWIcp6aATIHbrUDNqW9sb8BTBIA4ucHE6sKfZqAXWVGXlP6wI/AAPcEy5X53ljtbzYlEad0dz52BXfWk9B7yMWS3omIk9ISm/ayWYs773UiZQ7FNtK6eW4w1e3j9ncqkQarVyFE82+ihmwT9eVY1+B7PGSd4egOLnbI8PXk4o/JpNBT/qsFgtgQyBsnFr/hydaRzxtYIiQUviKZEl0FjX5YvCWiFEkrStZy02in/t4Tl6cOcxnQxbpu89aYzvIOpHgVEXuDUphLedvdZ0ljveBgoZELLJ14lgf0lDvnzVahgdCzj+sbIoKle+PFoCurq7WdlC9e/a4tVa8eDItaIp/fm2eiDJ0UDzqGtDv8gXYDB+XcDeVVFyqHXgNoFjt9pmEuXGQSi7Tv+tfnWuXwMxTR2HzrJ70ehsLV476IhIW3ttHpR9eK7nqt5wCD/SGU7TfRbMXwyvIsljAlhrl3u4PmECGUa4JwJ96UkmYQD8aUxCWHtks0DuylrTvtRsCg/CKM8/MDyAEYiBO8AoHHRJBdx7WssIqFigRzWlQhCzGLTi1aSYd1aPkdxVkPdvfzuwUaY2YoR3GYQP46YsHWNE=
