#!/usr/bin/env ruby
require "mechanize"
require "json"

module FetchCreatures
  def self.agent
    @agent ||= Mechanize.new
  end

  def self.write(data, file)
    File.write(
      File.join(Dir.pwd, "lib", "Olib", "combat", file), 
      JSON.pretty_generate(data))
  end

  def self.fetch_level_info(acc)
    html = Nokogiri::HTML agent.get(%(https://gswiki.play.net/Category:Creatures_by_Level)).content.toutf8
    html.css("td").map do |td|
      level = td.css("b").first.text.scan(/\d+/).first.to_i
      creatures = td.css("li").map(&:text).map(&:strip)
      creatures.each {|name|
        creature_info = acc[name.downcase] ||= {}
        creature_info.merge!({level: level})
      }
    end
  end

  def self.fetch_skin_info(acc)
    html = Nokogiri::HTML agent.get(%(https://gswiki.play.net/List_of_skins)).content.toutf8
    html.css("tr")[1..-1].each do |tr|
      (name, _level, skin) = tr.css("td").map(&:text).map(&:strip).map(&:downcase)
      acc.fetch(name)
      acc[name].merge!({skin: skin})
    end
  end

  def self.main()
    creatures = {}
    fetch_level_info(creatures)
    pp creatures
    fetch_skin_info(creatures)
    write(creatures, "creatures.json")
  end

  main()
end