#!/bin/bash

#sudo apt-get install jq

function parseSemver() {
    local RE='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
    #MAJOR
    eval $2=`echo $1 | sed -e "s#$RE#\1#"`
    #MINOR
    eval $3=`echo $1 | sed -e "s#$RE#\2#"`
    #MINOR
    eval $4=`echo $1 | sed -e "s#$RE#\3#"`
    #SPECIAL
    eval $5=`echo $1 | sed -e "s#$RE#\4#"`
}

PREVIOUS_VERION=$(curl -s https://rubygems.org/api/v1/versions/$GEM/latest.json | jq -r ".version")

MAJOR=0
MINOR=0
PATCH=0
SPECIAL=0

parseSemver $PREVIOUS_VERION MAJOR MINOR PATCH SPECIAL

echo $MAJOR
echo $MINOR
echo $PATCH
echo $SPECIAL